---
version: '3.5'
services:
  word-count-steamiz-app:
    build: ../src/word-count/
    container_name: word-count-steamiz
    hostname: word-count-steamiz
    environment:
      - KAFKA_BOOTSTRAP_SERVER=broker:29092
    depends_on:
      - broker