---
version: '3.5'
services:
  de-deduplication-steamiz-app:
    build: ../src/de-duplication/
    container_name: de-deduplication-steamiz
    hostname: de-deduplication-steamiz
    environment:
      - KAFKA_BOOTSTRAP_SERVER=broker:29092
    depends_on:
      - broker