---
version: '3.5'
services:
  global-ktable-steamiz-app:
    build: ../src/global-ktable/
    container_name: global-ktable-steamiz
    hostname: global-ktable-steamiz
    environment:
      - KAFKA_BOOTSTRAP_SERVER=broker:29092
      - KAFKA_SCHEMA_REGISTRY_URL=http://schema-registry:8081
    depends_on:
      - broker